-- AlterTable
ALTER TABLE "Comment" ADD COLUMN     "commentLikesCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Twit" ADD COLUMN     "commentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "likeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "retwitCount" INTEGER NOT NULL DEFAULT 0;
